name: Nightwatch Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: mkdir -p screens logs
    - run: sudo apt-get install xvfb
    - name: Run Nightwatch tests
      run: xvfb-run --auto-servernum npm test -- --env chrome

    - name: upload report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: nightwatch-html-report
        path: tests_output/nightwatch-html-report/index.html

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: Logs
        path: logs/
        retention-days: 1

    - name: Display structure of log files
      if: always()
      run: ls -R
      working-directory: logs/